12 - Desenvolvimento fullstack com Django/desafio/cards/urls.py
from django.urls import path

from . import views

app_name = "cards"
urlpatterns = [
    path("request-card/", views.request_card, name="request_card"),
    path("my-requests/", views.view_requests, name="view_requests"),
    path("request-details/<int:card_id>/", views.card_details, name="card_details"),
]

12 - Desenvolvimento fullstack com Django/desafio/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("cards/", include("cards.urls", namespace="cards")),
]

12 - Desenvolvimento fullstack com Django/desafio/cards/models.py
from django.contrib.auth.models import User
from django.db import models


class Card(models.Model):
    STATUS_CHOICES = (
        ("P", "Pendente"),
        ("A", "Aprovado"),
        ("E", "Enviado"),
        ("R", "Recebido"),
    )

    CARD_NETWORK = (
        ("V", "Visa"),
        ("M", "Mastercard"),
    )

    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="cards", verbose_name="Usuário")
    name = models.CharField("Nome", max_length=20)
    number = models.CharField("Número", max_length=16)
    holder_name = models.CharField("Titular", max_length=20)
    network = models.CharField("Rede", max_length=1, choices=CARD_NETWORK)
    expiration_date = models.CharField("Data de expiração", max_length=5)
    cvv = models.CharField("CVV", max_length=4)
    status = models.CharField("Status", max_length=1, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])
    created_at = models.DateTimeField("Criado em", auto_now_add=True)
    updated_at = models.DateTimeField("Alterado em", auto_now=True)

    def __str__(self) -> str:
        return f"Cartão {self.id} - {self.user.username} - {self.get_status_display()}"

    class Meta:
        verbose_name_plural = "Cartões"
        ordering = ["-created_at"]

12 - Desenvolvimento fullstack com Django/desafio/cards/forms.py
from django import forms

from .models import Card


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ["holder_name"]

12 - Desenvolvimento fullstack com Django/desafio/cards/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CardForm
from .models import Card


@login_required
def request_card(request):
    def generate_card_info() -> dict[str, str]:
        import random
        from datetime import UTC, datetime

        cc_month = str(random.randint(1, 12)).zfill(2)
        cc_year = str(datetime.now(UTC).year + 10)[2:]
        return {
            "name": "DIO Bank Platinum",
            "number": "".join([str(random.randint(0, 9)) for _ in range(16)]),
            "network": random.choice(["V", "M"]),
            "expiration_date": f"{cc_month}/{cc_year}",
            "cvv": "".join([str(random.randint(0, 9)) for _ in range(3)]),
        }

    if request.method == "POST":
        form = CardForm(request.POST)
        if form.is_valid():
            card_info = generate_card_info()

            card_request = form.save(commit=False)
            card_request.user = request.user
            card_request.name = card_info["name"]
            card_request.number = card_info["number"]
            card_request.network = card_info["network"]
            card_request.expiration_date = card_info["expiration_date"]
            card_request.cvv = card_info["cvv"]
            card_request.save()

            return redirect(reverse("cards:view_requests"))
    else:
        form = CardForm()
    return render(request, "cards/request_card.html", {"form": form})


@login_required
def view_requests(request):
    user_requests = Card.objects.filter(user=request.user).order_by("-created_at")
    return render(request, "cards/view_requests.html", {"user_requests": user_requests})


@login_required
def card_details(request, card_id):
    card = get_object_or_404(Card, id=card_id, user=request.user)
    return render(request, "cards/card_details.html", {"card": card})

12 - Desenvolvimento fullstack com Django/desafio/cards/templates/cards/card_details.html
{% extends 'base.html' %}

{% block content %}
<h2 class="my-4">Detalhes da Solicitação do Cartão</h2>
<div class="card" style="width: 20rem;">
  <div class="card-body">
    <h5 class="card-title">{{ card.name }}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">**** **** **** {{ card.number|slice:"12:" }}</h6>
    <p class="card-text">{{ card.holder_name }}</p>
    <span class="badge text-bg-{%if card.network == 'M'%}danger{% else %}primary{%endif%}">{{ card.get_network_display }}</span>
    <span class="badge text-bg-{%if card.status == 'P'%}secondary{%endif%}{%if card.status == 'A'%}dark{%endif%}{%if card.status == 'E'%}info{%endif%}{%if card.status == 'R'%}success{%endif%}">{{ card.get_status_display }}</span>
  </div>
</div>
<a class="d-block mt-4" href="{% url 'cards:view_requests' %}">Voltar às solicitações</a>
{% endblock %}

12 - Desenvolvimento fullstack com Django/desafio/cards/templates/cards/request_card.html
{% extends 'base.html' %}

{% block title %}Solicitar novo cartão{% endblock %}

{% load widget_tweaks %}

{% block content %}
<p><a href="{% url 'cards:view_requests' %}">Voltar</a></p>
<h2 class="my-4">Solicitar Novo Cartão</h2>
<div>
  <form method="post" novalidate class="w-25">
    {% csrf_token %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          <div class="invalid-feedback">
            {{ field.errors|first }}
          </div>
        {% else %}
          {% render_field field class="form-control" %}
          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Enviar Solicitação</button>
  </form>
</div>
{% endblock %}

12 - Desenvolvimento fullstack com Django/desafio/cards/templates/cards/view_requests.html
{% extends 'base.html' %}

{% block content %}
<p>
  <a href="{% url 'home' %}">Início</a> |
  <a href="{% url 'cards:request_card' %}">Solicitar cartão</a>
</p>
<h2 class="my-4">Minhas Solicitações de Cartão</h2>
{% if user_requests %}
  <div class="list-group">
    {% for request in user_requests %}
    <a href="{% url 'cards:card_details' request.id %}" class="list-group-item list-group-item-action">
      Solicitação feita em: {{ request.created_at }} - Status: {{ request.get_status_display }}
    </a>
    {% endfor %}
  </div>
{% else %}
  <p>Você não tem solicitações de cartão.</p>
{% endif %}
{% endblock %}

12 - Desenvolvimento fullstack com Django/desafio/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Desafio Django{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <main class="container">
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </main>
</body>
</html>

12 - Desenvolvimento fullstack com Django/desafio/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <p><a href="{% url 'cards:view_requests' %}">Minhas solicitações</a></p>
    <p>Olá {{ user.username }}!</p>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-secondary">Sair</button>
    </form>
  {% else %}
    <p>Você não está logado</p>
    <a href="{% url 'login' %}" class="btn btn-primary">Entrar</a>
  {% endif %}
{% endblock %}