12 - Desenvolvimento fullstack com Django/mysite/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.authenticate_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

12 - Desenvolvimento fullstack com Django/mysite/config/urls.py
from config.admin import admin_site
from django.urls import include, path

urlpatterns = [
    path("admin/", admin_site.urls),
    path("polls/", include("polls.urls")),
    path("contacts/", include("contacts.urls")),
    path("accounts/", include("accounts.urls")),
]

12 - Desenvolvimento fullstack com Django/mysite/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"
urlpatterns = [
    path("", views.get_name, name="get_name"),
    path("thanks/<str:name>", views.thanks, name="thanks"),
    path("create/", views.create, name="create"),
]

12 - Desenvolvimento fullstack com Django/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

12 - Desenvolvimento fullstack com Django/mysite/contacts/models.py
from django.db import models


class Contact(models.Model):
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=250)
    sender = models.EmailField()
    cc_myself = models.BooleanField(null=True, blank=True)

12 - Desenvolvimento fullstack com Django/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField("Texto da questão", max_length=200)
    pub_date = models.DateTimeField("Data da publicação")
    active = models.BooleanField("Ativo", default=True)

    class Meta:
        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self) -> str:
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Questão")
    choice_text = models.CharField("Descrição", max_length=200)
    votes = models.IntegerField("Votos", default=0)

    class Meta:
        verbose_name = "Opção"
        verbose_name_plural = "Opções"

    def __str__(self) -> str:
        return self.choice_text

12 - Desenvolvimento fullstack com Django/mysite/contacts/forms.py
from django import forms

from .models import Contact


class NameForm(forms.Form):
    your_name = forms.CharField(label="Seu nome", max_length=100)


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

12 - Desenvolvimento fullstack com Django/mysite/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def authenticate_user(request):
    context = {}

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("contacts:create"))
        else:
            context["message"] = "Usuário ou senha inválidos!"
            return render(request, "accounts/login.html", context)

    return render(request, "accounts/login.html", context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("accounts:login"))

12 - Desenvolvimento fullstack com Django/mysite/contacts/views.py
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import ContactForm, NameForm


@permission_required("contacts.add_contact")
def create(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["subject"]
            form.save()
            return HttpResponseRedirect(reverse("contacts:thanks", args=(name,)))
    else:
        form = ContactForm()
    return render(request, "contacts/create.html", {"form": form})


def get_name(request):
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["your_name"]
            return HttpResponseRedirect(reverse("contacts:thanks", args=(name,)))
    else:
        form = NameForm()
    return render(request, "contacts/name.html", {"form": form})


def thanks(request, name):
    return HttpResponse(f"Obrigado {name}!")

12 - Desenvolvimento fullstack com Django/mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from polls.models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list,
    }
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "Você não selecionou nenhuma opção.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

12 - Desenvolvimento fullstack com Django/mysite/accounts/templates/accounts/login.html
<h1>Login</h1>
{% if message %}
<p style="color: red;">{{message}}</p>
{% endif %}
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" id="username">
    <input type="password" name="password" id="password">
    <input type="submit" value="Entrar">
</form>

12 - Desenvolvimento fullstack com Django/mysite/contacts/templates/contacts/create.html
<a href="{% url 'accounts:logout' %}">Sair</a>
<form action="{%url 'contacts:create' %}" method="post" novalidate>
    {%csrf_token%}
    {{form}}
    <input type="submit" value="Enviar">
</form>

12 - Desenvolvimento fullstack com Django/mysite/contacts/templates/contacts/name.html
<form action="{% url 'contacts:get_name' %}" method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

12 - Desenvolvimento fullstack com Django/mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

12 - Desenvolvimento fullstack com Django/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma enquete foi criada.</p>
{% endif %}

12 - Desenvolvimento fullstack com Django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} voto{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote novamente?</a>